In [1]:
#load dataset yang akan digunakan 
import pandas as pd
df = pd.read_csv("data/data.csv", sep=';') 
print("âœ… Dataset berhasil diload")
print(f"Shape: {df.shape}")
df

âœ… Dataset berhasil diload
Shape: (4424, 37)

,Marital_status,Application_mode,Application_order,Course,Daytime_evening_attendance,Previous_qualification,Previous_qualification_grade,Nacionality,Mothers_qualification,Fathers_qualification,...,Curricular_units_2nd_sem_credited,Curricular_units_2nd_sem_enrolled,Curricular_units_2nd_sem_evaluations,Curricular_units_2nd_sem_approved,Curricular_units_2nd_sem_grade,Curricular_units_2nd_sem_without_evaluations,Unemployment_rate,Inflation_rate,GDP,Status
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4419,1,1,6,9773,1,1,125.0,1,1,1,...,0,6,8,5,12.666667,0,15.5,2.8,-4.06,Graduate
4420,1,1,2,9773,1,1,120.0,105,1,1,...,0,6,6,2,11.000000,0,11.1,0.6,2.02,Dropout
4421,1,1,1,9500,1,1,154.0,1,37,37,...,0,8,9,1,13.500000,0,13.9,-0.3,0.79,Dropout
4422,1,1,1,9147,1,1,180.0,1,37,37,...,0,5,6,5,12.000000,0,9.4,-0.8,-3.12,Graduate
4423,1,10,1,9773,1,1,152.0,22,38,37,...,0,6,6,6,13.000000,0,12.7,3.7,-1.70,Graduate

In [2]:
# Mapping dictionary untuk masing-masing kolom kategorikal

marital_status_map = {
    1: "Single", 2: "Married", 3: "Widower", 4: "Divorced",
    5: "Facto Union", 6: "Legally Separated"
}

application_mode_map = {
    1: "1st phase - general contingent",
    2: "Ordinance No. 612/93",
    5: "1st phase - special contingent (Azores Island)",
    7: "Holders of other higher courses",
    10: "Ordinance No. 854-B/99",
    15: "International student (bachelor)",
    16: "1st phase - special contingent (Madeira Island)",
    17: "2nd phase - general contingent",
    18: "3rd phase - general contingent",
    26: "Ordinance No. 533-A/99, item b2)",
    27: "Ordinance No. 533-A/99, item b3",
    39: "Over 23 years old",
    42: "Transfer",
    43: "Change of course",
    44: "Technological specialization diploma holders",
    51: "Change of institution/course",
    53: "Short cycle diploma holders",
    57: "Change of institution/course (International)"
}

course_map = {
    33: "Biofuel Production Technologies",
    171: "Animation and Multimedia Design",
    8014: "Social Service (evening)",
    9003: "Agronomy",
    9070: "Communication Design",
    9085: "Veterinary Nursing",
    9119: "Informatics Engineering",
    9130: "Equinculture",
    9147: "Management",
    9238: "Social Service",
    9254: "Tourism",
    9500: "Nursing",
    9556: "Oral Hygiene",
    9670: "Advertising and Marketing Management",
    9773: "Journalism and Communication",
    9853: "Basic Education",
    9991: "Management (evening)"
}

attendance_map = {0: "Evening", 1: "Daytime"}

nationality_map = {
    1: "Portuguese", 2: "German", 6: "Spanish", 11: "Italian", 13: "Dutch", 14: "English", 17: "Lithuanian",
    21: "Angolan", 22: "Cape Verdean", 24: "Guinean", 25: "Mozambican", 26: "Santomean", 32: "Turkish",
    41: "Brazilian", 62: "Romanian", 100: "Moldovan", 101: "Mexican", 103: "Ukrainian", 105: "Russian",
    108: "Cuban", 109: "Colombian"
}

# Boolean fields (binary categorical)
boolean_map = {0: "No", 1: "Yes"}
gender_map = {0: "Female", 1: "Male"}


# Mapping kolom dengan dictionary
df['Marital_status'] = df['Marital_status'].map(marital_status_map)
df['Application_mode'] = df['Application_mode'].map(application_mode_map)
df['Course'] = df['Course'].map(course_map)
df['Daytime_evening_attendance'] = df['Daytime_evening_attendance'].map(attendance_map)
df['Nacionality'] = df['Nacionality'].map(nationality_map)
df['Displaced'] = df['Displaced'].map(boolean_map)
df['Educational_special_needs'] = df['Educational_special_needs'].map(boolean_map)
df['Debtor'] = df['Debtor'].map(boolean_map)
df['Tuition_fees_up_to_date'] = df['Tuition_fees_up_to_date'].map(boolean_map)
df['Gender'] = df['Gender'].map(gender_map)
df['Scholarship_holder'] = df['Scholarship_holder'].map(boolean_map)
df['International'] = df['International'].map(boolean_map)

df

,Marital_status,Application_mode,Application_order,Course,Daytime_evening_attendance,Previous_qualification,Previous_qualification_grade,Nacionality,Mothers_qualification,Fathers_qualification,...,Curricular_units_2nd_sem_credited,Curricular_units_2nd_sem_enrolled,Curricular_units_2nd_sem_evaluations,Curricular_units_2nd_sem_approved,Curricular_units_2nd_sem_grade,Curricular_units_2nd_sem_without_evaluations,Unemployment_rate,Inflation_rate,GDP,Status
0,Single,2nd phase - general contingent,5,Animation and Multimedia Design,Daytime,1,122.0,Portuguese,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,Single,International student (bachelor),1,Tourism,Daytime,1,160.0,Portuguese,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,Single,1st phase - general contingent,5,Communication Design,Daytime,1,122.0,Portuguese,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,Single,2nd phase - general contingent,2,Journalism and Communication,Daytime,1,122.0,Portuguese,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,Married,Over 23 years old,1,Social Service (evening),Evening,1,100.0,Portuguese,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4419,Single,1st phase - general contingent,6,Journalism and Communication,Daytime,1,125.0,Portuguese,1,1,...,0,6,8,5,12.666667,0,15.5,2.8,-4.06,Graduate
4420,Single,1st phase - general contingent,2,Journalism and Communication,Daytime,1,120.0,Russian,1,1,...,0,6,6,2,11.000000,0,11.1,0.6,2.02,Dropout
4421,Single,1st phase - general contingent,1,Nursing,Daytime,1,154.0,Portuguese,37,37,...,0,8,9,1,13.500000,0,13.9,-0.3,0.79,Dropout
4422,Single,1st phase - general contingent,1,Management,Daytime,1,180.0,Portuguese,37,37,...,0,5,6,5,12.000000,0,9.4,-0.8,-3.12,Graduate
4423,Single,Ordinance No. 854-B/99,1,Journalism and Communication,Daytime,1,152.0,Cape Verdean,38,37,...,0,6,6,6,13.000000,0,12.7,3.7,-1.70,Graduate

In [3]:
df.to_csv("data/data_mapped.csv", index=False)
print("âœ… Dataset berhasil dimapping dan disimpan sebagai 'data/data_mapped.csv'")

âœ… Dataset berhasil dimapping dan disimpan sebagai 'data/data_mapped.csv'